// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Uksbs.Connect.AutomatedTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MyTeamFeature : object, Xunit.IClassFixture<MyTeamFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MyTeam.feature"
#line hidden
        
        public MyTeamFeature(MyTeamFeature.FixtureData fixtureData, Uksbs_Connect_AutomatedTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "MyTeam", "\tI should be able to: login, and to see My Team tile. \r\n\tAnd also I should  be ab" +
                    "le to change the line manager of my employee.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="01 Perform my team scenarios")]
        [Xunit.TraitAttribute("FeatureTitle", "MyTeam")]
        [Xunit.TraitAttribute("Description", "01 Perform my team scenarios")]
        [Xunit.TraitAttribute("Category", "connect-regression1")]
        [Xunit.TraitAttribute("Category", "myteam")]
        [Xunit.TraitAttribute("Category", "boe")]
        [Xunit.InlineDataAttribute("5", "People", "Mark Norris", "Policy Delivery", "Keith Hodgkinson", "Policy Delivery", "Keith.Hodgkinson@tst1.uksbs.co.uk", "My Manager", "BIS-Senior Civil Service.Pay Band 1", new string[0])]
        public void _01PerformMyTeamScenarios(string noInPieChart, string directsInPieChart, string myName, string myPosition, string myManagerName, string myManagerPosition, string myManagerEmail, string managerTitle, string managerGrade, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "connect-regression1",
                    "myteam",
                    "boe"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("noInPieChart", noInPieChart);
            argumentsOfScenario.Add("directsInPieChart", directsInPieChart);
            argumentsOfScenario.Add("myName", myName);
            argumentsOfScenario.Add("myPosition", myPosition);
            argumentsOfScenario.Add("myManagerName", myManagerName);
            argumentsOfScenario.Add("myManagerPosition", myManagerPosition);
            argumentsOfScenario.Add("myManagerEmail", myManagerEmail);
            argumentsOfScenario.Add("managerTitle", managerTitle);
            argumentsOfScenario.Add("managerGrade", managerGrade);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 Perform my team scenarios", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given("I login as an employee", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.Then("I should see my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
 testRunner.And("I should see pie chart in my team tile left side", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.And(string.Format("I should see number of directs in pie chart as \"{0}\"", noInPieChart), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 testRunner.And(string.Format("I should see directs in pie chart as \"{0}\"", directsInPieChart), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.And(string.Format("I should see my name in my team tile as \"{0}\"", myName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
 testRunner.And(string.Format("I should see my position in my team tile as \"{0}\"", myPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.And(string.Format("I should see my manager name in my team tile as \"{0}\"", myManagerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.And(string.Format("I should see my manager position in my team tile as \"{0}\"", myManagerPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
 testRunner.When(string.Format("I click on the manager in my team tile right side as \"{0}\"", myManagerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
 testRunner.Then(string.Format("I should see manager name in my team tile back as \"{0}\"", myManagerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
 testRunner.And(string.Format("I should see manager position in my team tile back as \"{0}\"", myManagerPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
 testRunner.And(string.Format("I should see manager email in my team tile back as \"{0}\"", myManagerEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
 testRunner.When("I click back button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
 testRunner.Then("the tile flips back to my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
 testRunner.When("I click on view my team", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
 testRunner.Then("I will be redirected to the team view page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
 testRunner.And(string.Format("I should see title of manager in team view as \"{0}\"", managerTitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
 testRunner.And(string.Format("I should see my manager name in team view as \"{0}\"", myManagerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
 testRunner.And(string.Format("I should see my manager position in team view as \"{0}\"", myManagerPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
 testRunner.And(string.Format("I should see my manager grade in team view as \"{0}\"", managerGrade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
 testRunner.When("I mouse over the tile that has my manager name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
 testRunner.Then(string.Format("I should see my manager email as \"{0}\"", myManagerEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="02 Perform my team scenarios with manager credentials")]
        [Xunit.TraitAttribute("FeatureTitle", "MyTeam")]
        [Xunit.TraitAttribute("Description", "02 Perform my team scenarios with manager credentials")]
        [Xunit.TraitAttribute("Category", "connect-regression1")]
        [Xunit.TraitAttribute("Category", "myteam")]
        [Xunit.TraitAttribute("Category", "boe")]
        [Xunit.InlineDataAttribute("5", "people", "Mark Norris", "Policy Delivery", "mark.norris@tst1.uksbs.co.uk", "0747085499", "My Manager", "Hannah Boardman", "Policy Delivery", "BIS-Senior Civil Service.Pay Band 2", "", "Hannah.boardman@tst1.uksbs.co.uk", "Mark Norris", "0747085499", "mark.norris@tst1.uksbs.co.uk", "Policy Delivery", "Employee", "Policy Delivery", "BEIS - 1 Victoria Street", "Manufacturing, Defence and Marine - 102056", "102056", "BIS-G6 (New Terms).London", "100183", "Keith Hodgkinson", new string[0])]
        public void _02PerformMyTeamScenariosWithManagerCredentials(
                    string noInPieChart, 
                    string directsInPieChart, 
                    string teamMemberName, 
                    string teamMemberPosition, 
                    string teamMemberEmail, 
                    string teamMemberContact, 
                    string managerTitle, 
                    string managerName, 
                    string managerPosition, 
                    string managerGrade, 
                    string managerPhone, 
                    string managerEmail, 
                    string directReportName, 
                    string directReportPhone, 
                    string directReportEmail, 
                    string directReportPosition, 
                    string directReportType, 
                    string orgJob, 
                    string orgLocation, 
                    string orgDepartment, 
                    string orgCostCentre, 
                    string orgGrade, 
                    string orgProgramCode, 
                    string myName, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "connect-regression1",
                    "myteam",
                    "boe"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("noInPieChart", noInPieChart);
            argumentsOfScenario.Add("directsInPieChart", directsInPieChart);
            argumentsOfScenario.Add("teamMemberName", teamMemberName);
            argumentsOfScenario.Add("teamMemberPosition", teamMemberPosition);
            argumentsOfScenario.Add("teamMemberEmail", teamMemberEmail);
            argumentsOfScenario.Add("teamMemberContact", teamMemberContact);
            argumentsOfScenario.Add("managerTitle", managerTitle);
            argumentsOfScenario.Add("managerName", managerName);
            argumentsOfScenario.Add("managerPosition", managerPosition);
            argumentsOfScenario.Add("managerGrade", managerGrade);
            argumentsOfScenario.Add("managerPhone", managerPhone);
            argumentsOfScenario.Add("managerEmail", managerEmail);
            argumentsOfScenario.Add("directReportName", directReportName);
            argumentsOfScenario.Add("directReportPhone", directReportPhone);
            argumentsOfScenario.Add("directReportEmail", directReportEmail);
            argumentsOfScenario.Add("directReportPosition", directReportPosition);
            argumentsOfScenario.Add("directReportType", directReportType);
            argumentsOfScenario.Add("orgJob", orgJob);
            argumentsOfScenario.Add("orgLocation", orgLocation);
            argumentsOfScenario.Add("orgDepartment", orgDepartment);
            argumentsOfScenario.Add("orgCostCentre", orgCostCentre);
            argumentsOfScenario.Add("orgGrade", orgGrade);
            argumentsOfScenario.Add("orgProgramCode", orgProgramCode);
            argumentsOfScenario.Add("myName", myName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 Perform my team scenarios with manager credentials", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 62
 testRunner.Given("I login as manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 63
 testRunner.Then("I should see my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 64
 testRunner.And("I should see pie chart in my team tile left side", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 65
 testRunner.And("I should see number of directs in pie chart as \"5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
 testRunner.And("I should see directs in pie chart as \"People\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 67
 testRunner.When("I click navigation bullets", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 68
 testRunner.Then("I should see list of my team members", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 69
 testRunner.When(string.Format("I click on one of my team member as \"{0}\"", teamMemberName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 70
 testRunner.Then(string.Format("I should see team member name in my team tile back as \"{0}\"", teamMemberName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
 testRunner.And(string.Format("I should see team member position in my team tile back as \"{0}\"", teamMemberPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
 testRunner.And(string.Format("I should see team member email in my team tile back as \"{0}\"", teamMemberEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
 testRunner.And(string.Format("I should see team member telephone number in my team tile back as \"{0}\"", teamMemberContact), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
 testRunner.When("I click back button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 75
 testRunner.Then("the tile flips back to my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
 testRunner.When("I click on view my team", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 80
 testRunner.Then("I will be redirected to the team view page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 81
 testRunner.And(string.Format("I should see title of manager in team view as \"{0}\"", managerTitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 82
 testRunner.And(string.Format("I should see my manager name in team view as \"{0}\"", managerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 83
 testRunner.And(string.Format("I should see my manager position in team view as \"{0}\"", managerPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
 testRunner.And(string.Format("I should see my manager grade in team view as \"{0}\"", managerGrade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
 testRunner.When("I mouse over the tile that has my manager name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 87
 testRunner.Then(string.Format("I should see my manager work telephone number as \"{0}\"", managerPhone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
 testRunner.And(string.Format("I should see my manager email as \"{0}\"", managerEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 89
 testRunner.When(string.Format("I mouse over the tile that has my direct reports as \"{0}\"", directReportName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 90
 testRunner.Then(string.Format("I should see my direct reports work telephone number as \"{0}\"", directReportPhone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 91
 testRunner.And(string.Format("I should see my direct reports email as \"{0}\"", directReportEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 92
 testRunner.When(string.Format("I click on view profile as \"{0}\"", directReportName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
 testRunner.Then("I will be redirected to the profile screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
 testRunner.And(string.Format("I should see full name as \"{0}\"", directReportName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 95
 testRunner.And(string.Format("I should see job description as \"{0}\"", directReportPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 96
 testRunner.And(string.Format("I should see person type as \"{0}\"", directReportType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 98
 testRunner.And(string.Format("I should see work email address as \"{0}\"", directReportEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 99
 testRunner.And(string.Format("I should see work phone number as \"{0}\"", directReportPhone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 100
 testRunner.And(string.Format("I should see organisation job description as \"{0}\"", orgJob), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 101
 testRunner.And(string.Format("I should see organisation location as \"{0}\"", orgLocation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 102
 testRunner.And(string.Format("I should see organisation department as \"{0}\"", orgDepartment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 103
 testRunner.And(string.Format("I should see organisation department cost centre as \"{0}\"", orgCostCentre), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 104
 testRunner.And(string.Format("I should see organisation grade as \"{0}\"", orgGrade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 105
 testRunner.And(string.Format("I should see organisation employee programme code as \"{0}\"", orgProgramCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 106
 testRunner.And("I should see manager tile title as \"Manager\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 107
 testRunner.And(string.Format("I should see manager name as \"{0}\"", myName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 108
 testRunner.And(string.Format("I should see manager position as \"{0}\"", managerPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 109
 testRunner.And("I should see number of direct reports as \"Reports\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 110
 testRunner.And("I should see number of total reports as \"3 directs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 111
 testRunner.When("I click on how to update organizational information’", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 112
 testRunner.Then("I should see dialog window as \"Updating Organisational Data\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
 testRunner.And("I close dialog window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 114
 testRunner.When("I click on manager to update line manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="03 Perform my team scenarios with updated employee credentials")]
        [Xunit.TraitAttribute("FeatureTitle", "MyTeam")]
        [Xunit.TraitAttribute("Description", "03 Perform my team scenarios with updated employee credentials")]
        [Xunit.TraitAttribute("Category", "connect-regression1")]
        [Xunit.TraitAttribute("Category", "myteam")]
        [Xunit.TraitAttribute("Category", "boe")]
        [Xunit.InlineDataAttribute("2", "People", "George Pritchard", "Policy Delivery", "Tobias Lin", "Policy Delivery", "Tobias.Lin@tst1.uksbs.co.uk", new string[0])]
        public void _03PerformMyTeamScenariosWithUpdatedEmployeeCredentials(string noInPieChart, string directsInPieChart, string myName, string myPosition, string myManagerName, string myManagerPosition, string myManagerEmail, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "connect-regression1",
                    "myteam",
                    "boe"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("noInPieChart", noInPieChart);
            argumentsOfScenario.Add("directsInPieChart", directsInPieChart);
            argumentsOfScenario.Add("myName", myName);
            argumentsOfScenario.Add("myPosition", myPosition);
            argumentsOfScenario.Add("myManagerName", myManagerName);
            argumentsOfScenario.Add("myManagerPosition", myManagerPosition);
            argumentsOfScenario.Add("myManagerEmail", myManagerEmail);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 Perform my team scenarios with updated employee credentials", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 125
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 126
 testRunner.Given("I launch the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "UserName",
                            "Password"});
                table1.AddRow(new string[] {
                            "GPRITCHA28",
                            "CIIPproject123"});
#line 127
 testRunner.And("I enter the following details", ((string)(null)), table1, "And ");
#line hidden
#line 130
 testRunner.And("I click login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 131
 testRunner.Then("I should see my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 132
 testRunner.And("I should see pie chart in my team tile left side", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 133
 testRunner.And(string.Format("I should see number of directs in pie chart as \"{0}\"", noInPieChart), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 134
 testRunner.And(string.Format("I should see directs in pie chart as \"{0}\"", directsInPieChart), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 135
 testRunner.And(string.Format("I should see my name in my team tile as \"{0}\"", myName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 136
 testRunner.And(string.Format("I should see my position in my team tile as \"{0}\"", myPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 137
 testRunner.And(string.Format("I should see my manager name in my team tile as \"{0}\"", myManagerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 138
 testRunner.And(string.Format("I should see my manager position in my team tile as \"{0}\"", myManagerPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 139
 testRunner.When(string.Format("I click on the manager in my team tile right side as \"{0}\"", myManagerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 140
 testRunner.Then(string.Format("I should see manager name in my team tile back as \"{0}\"", myManagerName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 141
 testRunner.And(string.Format("I should see manager position in my team tile back as \"{0}\"", myManagerPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 142
 testRunner.And(string.Format("I should see manager email in my team tile back as \"{0}\"", myManagerEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 143
 testRunner.When("I click back button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 144
 testRunner.Then("the tile flips back to my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="04 Perform my team scenarios with updated manager credentials")]
        [Xunit.TraitAttribute("FeatureTitle", "MyTeam")]
        [Xunit.TraitAttribute("Description", "04 Perform my team scenarios with updated manager credentials")]
        [Xunit.TraitAttribute("Category", "connect-regression1")]
        [Xunit.TraitAttribute("Category", "myteam")]
        [Xunit.TraitAttribute("Category", "boe")]
        [Xunit.InlineDataAttribute("George Pritchard", "Work Tel: 07795 012687", "george.pritchard@tst1.uksbs.co.uk", "Policy Delivery", "Polaris House", "UKSA - Commercial - 110005 - Admin", "110005", "UKSA-G7 (New Terms).National", "", "", new string[0])]
        public void _04PerformMyTeamScenariosWithUpdatedManagerCredentials(string directReports, string directReportTelephone, string directReportEmail, string myPosition, string orgLocation, string orgDepartment, string orgCostCentre, string orgGrade, string orgProgramCode, string myName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "connect-regression1",
                    "myteam",
                    "boe"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("directReports", directReports);
            argumentsOfScenario.Add("directReportTelephone", directReportTelephone);
            argumentsOfScenario.Add("directReportEmail", directReportEmail);
            argumentsOfScenario.Add("myPosition", myPosition);
            argumentsOfScenario.Add("orgLocation", orgLocation);
            argumentsOfScenario.Add("orgDepartment", orgDepartment);
            argumentsOfScenario.Add("orgCostCentre", orgCostCentre);
            argumentsOfScenario.Add("orgGrade", orgGrade);
            argumentsOfScenario.Add("orgProgramCode", orgProgramCode);
            argumentsOfScenario.Add("myName", myName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 Perform my team scenarios with updated manager credentials", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 152
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 153
 testRunner.Given("I launch the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "UserName",
                            "Password"});
                table2.AddRow(new string[] {
                            "CBARCHAM33",
                            "CIIPproject123"});
#line 154
 testRunner.And("I enter the following details", ((string)(null)), table2, "And ");
#line hidden
#line 157
 testRunner.And("I click login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 158
 testRunner.Then("I should see my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 159
 testRunner.When("I click on view my team", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 160
 testRunner.Then("I will be redirected to the team view page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 161
 testRunner.And("I should see title in team view as \"My Direct Reports\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 162
 testRunner.When(string.Format("I mouse over the tile that has my direct reports as \"{0}\"", directReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 163
 testRunner.Then(string.Format("I should see my direct reports work telephone number as \"{0}\"", directReportTelephone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 164
 testRunner.And(string.Format("I should see my direct reports email as \"{0}\"", directReportEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 165
 testRunner.When(string.Format("I click on view profile as \"{0}\"", directReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 166
 testRunner.Then("I will be redirected to the profile screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 167
 testRunner.And(string.Format("I should see my full name as \"{0}\"", directReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 168
 testRunner.And(string.Format("I should see my job description as \"{0}\"", myPosition), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 169
 testRunner.And("I should see person type as \"Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 170
 testRunner.And("I should see work location address as |\"Polaris House\" \"North Star Avenue\" \"Swind" +
                        "on\" \"SN2 1SZ\"|", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 171
 testRunner.And(string.Format("I should see work email address as \"{0}\"", directReportEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 172
 testRunner.And(string.Format("I should see work phone number as \"{0}\"", directReportTelephone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 173
 testRunner.And("I should see organisation job description as \"Policy Delivery\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 174
 testRunner.And(string.Format("I should see organisation location as \"{0}\"", orgLocation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 175
 testRunner.And(string.Format("I should see organisation department as \"{0}\"", orgDepartment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 176
 testRunner.And(string.Format("I should see organisation department cost centre as \"{0}\"", orgCostCentre), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 177
 testRunner.And(string.Format("I should see organisation grade as \"{0}\"", orgGrade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 178
 testRunner.And(string.Format("I should see organisation employee programme code as \"{0}\"", orgProgramCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 179
 testRunner.And("I should see manager tile title as \"Manager\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 180
 testRunner.And("I should see manager name as \"Claire Barcham\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 181
 testRunner.And("I should see manager position as \"Programme and Project Management (PPM)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 182
 testRunner.And("I should see number of direct reports as \"Reports\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 183
 testRunner.And("I should see number of total reports as \"7 directs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 184
 testRunner.When("I click on how to update organizational information’", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 185
 testRunner.Then("I should see dialog window as \"Updating Organisational Data\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 186
 testRunner.And("I close dialog window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="05 Perform my team scenarios with updated manager credentials with future date")]
        [Xunit.TraitAttribute("FeatureTitle", "MyTeam")]
        [Xunit.TraitAttribute("Description", "05 Perform my team scenarios with updated manager credentials with future date")]
        [Xunit.TraitAttribute("Category", "connect-regression1")]
        [Xunit.TraitAttribute("Category", "myteam")]
        [Xunit.TraitAttribute("Category", "boe")]
        [Xunit.InlineDataAttribute("George Pritchard", "Work Tel: 07795 012687", "george.pritchard@tst1.uksbs.co.uk", new string[0])]
        public void _05PerformMyTeamScenariosWithUpdatedManagerCredentialsWithFutureDate(string directReports, string directReportTelephone, string directReportEmail, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "connect-regression1",
                    "myteam",
                    "boe"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("directReports", directReports);
            argumentsOfScenario.Add("directReportTelephone", directReportTelephone);
            argumentsOfScenario.Add("directReportEmail", directReportEmail);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 Perform my team scenarios with updated manager credentials with future date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 193
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 194
 testRunner.Given("I launch the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "UserName",
                            "Password"});
                table3.AddRow(new string[] {
                            "CBARCHAM33",
                            "CIIPproject123"});
#line 195
 testRunner.And("I enter the following details", ((string)(null)), table3, "And ");
#line hidden
#line 198
 testRunner.And("I click login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 199
 testRunner.Then("I should see my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 200
 testRunner.When("I click on view my team", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 201
 testRunner.Then("I will be redirected to the team view page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 202
 testRunner.And("I should see title in team view as \"My Direct Reports\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 203
 testRunner.When(string.Format("I mouse over the tile that has my direct reports as \"{0}\"", directReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 204
 testRunner.Then(string.Format("I should see my direct reports work telephone number as \"{0}\"", directReportTelephone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 205
 testRunner.And(string.Format("I should see my direct reports email as \"{0}\"", directReportEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 206
 testRunner.When(string.Format("I click on view profile as \"{0}\"", directReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 207
 testRunner.Then("I will be redirected to the profile screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 208
 testRunner.And(string.Format("I should see my full name as \"{0}\"", directReports), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 209
 testRunner.When("I click on manager to update line manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 210
 testRunner.Then("I should see dialog window header as \"Change of Manager\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 211
 testRunner.And("I select new manager as \"Tobias Lin | UKSA - Commercial - 110005 - Programme\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 212
 testRunner.And("I select effective start date as \"23.10.20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 213
 testRunner.Then("I click submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="06 Perform my team scenarios with updated employee credentials afer future date")]
        [Xunit.TraitAttribute("FeatureTitle", "MyTeam")]
        [Xunit.TraitAttribute("Description", "06 Perform my team scenarios with updated employee credentials afer future date")]
        [Xunit.TraitAttribute("Category", "connect-regression1")]
        [Xunit.TraitAttribute("Category", "myteam")]
        [Xunit.TraitAttribute("Category", "boe")]
        [Xunit.InlineDataAttribute("George Pritchard", "Policy Delivery", "george.pritchard@tst1.uksbs.co.uk", new string[0])]
        public void _06PerformMyTeamScenariosWithUpdatedEmployeeCredentialsAferFutureDate(string myName, string myPosition, string directReportEmail, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "connect-regression1",
                    "myteam",
                    "boe"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("myName", myName);
            argumentsOfScenario.Add("myPosition", myPosition);
            argumentsOfScenario.Add("directReportEmail", directReportEmail);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 Perform my team scenarios with updated employee credentials afer future date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 221
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 222
 testRunner.Given("I launch the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "UserName",
                            "Password"});
                table4.AddRow(new string[] {
                            "GPRITCHA28",
                            "CIIPproject123"});
#line 223
 testRunner.And("I enter the following details", ((string)(null)), table4, "And ");
#line hidden
#line 226
 testRunner.And("I click login button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 227
 testRunner.Then("I should see my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 228
 testRunner.And("I should see pie chart in my team tile left side", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 229
 testRunner.And("I should see number of directs in pie chart as \"4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 230
 testRunner.And("I should see directs in pie chart as \"People\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 231
 testRunner.And("I should see my name in my team tile as \"George Pritchard\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 232
 testRunner.And("I should see my position in my team tile as \"Policy Delivery\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 233
 testRunner.And("I should not see my manager name in my team tile as \"Tobias Lin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 234
 testRunner.And("I should see my manager position in my team tile as \"Programme and Project Manage" +
                        "ment (PPM)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 235
 testRunner.When("I click on the manager in my team tile right side as \"Claire Barcham\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 236
 testRunner.Then("I should see manager name in my team tile back as \"Claire Barcham\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 237
 testRunner.And("I should see manager position in my team tile back as \"Programme and Project Mana" +
                        "gement (PPM)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 238
 testRunner.And("I should see manager email in my team tile back as \"claire.barcham@tst1.uksbs.co." +
                        "uk\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 239
 testRunner.When("I click back button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 240
 testRunner.Then("the tile flips back to my team tile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MyTeamFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MyTeamFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
